  name: CI
  on:
    push:
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
       with:
         java-version: adopt@1.8
      - name: Compile
        run: sbt +test
